import React, { useEffect, useState, useMemo } from "react";
import {
  collection,
  query,
  where,
  onSnapshot,
  doc,
  setDoc,
  deleteDoc,
  getDoc,
  updateDoc,
} from "firebase/firestore";
import { db } from "../../../../firebase/firebaseConfig";
import "./ClassTeacherManager.css";
import ClassDetailView from "./ClassTeacherManager/ClassDetailView";
import TeacherList from "./ClassTeacherManager/TeacherList";
import { buildYearScopedClassId, matchesAcademicYearScope, normalizeAcademicYear } from "../schoolYearUtils";

// =========================================
// CONFIG
// =========================================
const DEFAULT_SECTIONS = [
  { id: "1-5", label: "1 - 5", grades: [1, 2, 3, 4, 5] },
  { id: "6-9", label: "6 - 9", grades: [6, 7, 8, 9] },
  { id: "10-12", label: "10 - 12", grades: [10, 11, 12] },
];

const DIVISION_FORMATS = [
  { id: "alpha", label: "A, B, C" },
  { id: "alphaNum", label: "A1, A2, A3" },
  { id: "numeric", label: "1, 2, 3" },
  { id: "custom", label: "Custom prefix" },
];

const generateDivisions = (format, count, customPrefix) => {
  const total = Math.max(0, Number(count || 0));
  const prefix = String(customPrefix || "A").trim().toUpperCase() || "A";
  const list = [];

  for (let i = 1; i <= total; i += 1) {
    if (format === "alpha") {
      list.push(String.fromCharCode(64 + i));
    } else if (format === "alphaNum") {
      list.push(`A${i}`);
    } else if (format === "numeric") {
      list.push(String(i));
    } else {
      list.push(`${prefix}${i}`);
    }
  }

  return list;
};

// =========================================
// HELPER: Auto-create Roll Setup
// =========================================
const createDefaultRollSetup = async (schoolId, academicYear, className) => {
  try {
    const classId = buildYearScopedClassId({ schoolId, academicYear, className });
    const rollSetupRef = doc(db, "classes", classId, "meta", "rollSetup");

    const grade = parseInt(className.match(/^\d+/)?.[0] || "0", 10);
    const total = grade <= 5 ? 25 : grade <= 9 ? 35 : 40;

    const rollSnap = await getDoc(rollSetupRef);
    if (rollSnap.exists()) return;

    await setDoc(rollSetupRef, {
      studentCount: total,
      format: "numeric",
      prefix: "",
      range: { start: 1, end: total },
      createdAt: new Date(),
      autoGenerated: true,
    });
    console.log(`✅ Default roll setup created for ${className}`);
  } catch (err) {
    console.error("❌ Roll setup creation failed:", err);
  }
};

// =========================================
// MAIN COMPONENT
// =========================================
const ClassTeacherManager = ({ schoolId, school, academicYear = "" }) => {
  const [sections] = useState(DEFAULT_SECTIONS);
  const [activeSectionId, setActiveSectionId] = useState(DEFAULT_SECTIONS[0].id);
  const [classesMap, setClassesMap] = useState({});
  const [teachers, setTeachers] = useState([]);
  const [filteredTeachers, setFilteredTeachers] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [draggedTeacher, setDraggedTeacher] = useState(null);
  
  // 🔹 CHANGED: single selectedTeacher (null) to selectedTeachers (array [])
  const [selectedTeachers, setSelectedTeachers] = useState([]); 
  
  const [loading, setLoading] = useState(false);
  const [newDivisionInput, setNewDivisionInput] = useState({});
  const [openCreatorGrade, setOpenCreatorGrade] = useState(null);
  const [divisionFormatByGrade, setDivisionFormatByGrade] = useState({});
  const [divisionCountByGrade, setDivisionCountByGrade] = useState({});
  const [customPrefixByGrade, setCustomPrefixByGrade] = useState({});
  const [confirmModal, setConfirmModal] = useState(null);
  const [activeClassDetail, setActiveClassDetail] = useState(null);
  const normalizedAcademicYear = normalizeAcademicYear(academicYear);

  // Realtime Teachers
  useEffect(() => {
    if (!schoolId) return;
    const q = query(collection(db, "users"), where("schoolId", "==", schoolId));
    const unsub = onSnapshot(q, (snap) => {
      const list = snap.docs
        .map((d) => ({ id: d.id, ...d.data() }))
        .filter((t) => ["teacher", "class_teacher"].includes(t.role))
        .filter((t) => matchesAcademicYearScope(t, normalizedAcademicYear));
      setTeachers(list);
      setFilteredTeachers(list);
    });
    return () => unsub();
  }, [normalizedAcademicYear, schoolId]);

  // Realtime Classes
  useEffect(() => {
    if (!schoolId) return;
    const q = query(collection(db, "classes"), where("schoolId", "==", schoolId));
    const unsub = onSnapshot(q, (snap) => {
      const map = {};
      snap.docs.forEach((d) => {
        const data = d.data() || {};
        if (normalizedAcademicYear && normalizeAcademicYear(data.academicYear) !== normalizedAcademicYear) return;
        map[data.className] = { id: d.id, ...data };
      });
      setClassesMap(map);
    });
    return () => unsub();
  }, [normalizedAcademicYear, schoolId]);

  // Search Filter
  useEffect(() => {
    const lower = searchTerm.trim().toLowerCase();
    setFilteredTeachers(
      !lower
        ? teachers
        : teachers.filter(
            (t) =>
              (t.name || "").toLowerCase().includes(lower) ||
              (t.email || "").toLowerCase().includes(lower)
          )
    );
  }, [searchTerm, teachers]);

  const classDocId = (className) => buildYearScopedClassId({ schoolId, academicYear: normalizedAcademicYear, className });
  const activeSection = useMemo(
    () => sections.find((s) => s.id === activeSectionId),
    [sections, activeSectionId]
  );

  const getDivisionsForGrade = (grade) => {
    const gradeClasses = Object.values(classesMap).filter((c) => c.grade === grade);
    const divs = Array.from(
      new Set(gradeClasses.map((c) => c.division || c.className.replace(/^\d+/, "")))
    );
    return divs;
  };

  const getDivisionFormatForGrade = (grade) => divisionFormatByGrade[grade] || "alpha";
  const getDivisionCountForGrade = (grade) => divisionCountByGrade[grade] || 1;
  const getCustomPrefixForGrade = (grade) => customPrefixByGrade[grade] || "A";

  const openGradeCreator = (grade) => {
    setOpenCreatorGrade(grade);
    setDivisionFormatByGrade((prev) => ({ ...prev, [grade]: prev[grade] || "alpha" }));
    setDivisionCountByGrade((prev) => ({ ...prev, [grade]: prev[grade] || 1 }));
    setCustomPrefixByGrade((prev) => ({ ...prev, [grade]: prev[grade] || "A" }));
  };

  const closeGradeCreator = () => {
    setOpenCreatorGrade(null);
  };

  // ➕ Add new division
  const handleAddDivision = async (grade, divRaw) => {
    const division = (divRaw || "").trim().toUpperCase();
    if (!division) return alert("Enter valid division");
    const className = `${grade}${division}`;
    setLoading(true);
    try {
      const ref = doc(db, "classes", classDocId(className));
      const snap = await getDoc(ref);
      if (snap.exists()) {
        alert(`${className} already exists`);
      } else {
        await setDoc(ref, {
          schoolId,
          academicYear: normalizedAcademicYear,
          className,
          grade,
          division,
          sectionId: activeSectionId,
          createdAt: new Date(),
        });
      }
      setNewDivisionInput((p) => ({ ...p, [grade]: "" }));
    } catch (err) {
      console.error("Error adding division", err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateGradeClasses = async (grade) => {
    if (!schoolId) return;

    const format = getDivisionFormatForGrade(grade);
    const count = Math.max(1, Number(divisionCountByGrade[grade] || 1));
    const customPrefix = getCustomPrefixForGrade(grade);
    const divisions = generateDivisions(format, count, customPrefix);

    setLoading(true);
    try {
      for (const division of divisions) {
        const className = `${grade}${division}`;
        const ref = doc(db, "classes", classDocId(className));
        const snap = await getDoc(ref);

        if (snap.exists()) continue;

        await setDoc(ref, {
          schoolId,
          academicYear: normalizedAcademicYear,
          className,
          grade,
          division,
          totalDivisions: count,
          divisionFormat: format,
          customPrefix: format === "custom" ? customPrefix : "",
          sectionId: activeSectionId,
          createdAt: new Date(),
        });
      }

      closeGradeCreator();
    } catch (err) {
      console.error("Class creation failed", err);
    } finally {
      setLoading(false);
    }
  };

  // 👩‍🏫 Assign teacher (Modified to handle selection reset)
  const assignTeacher = async (className, teacher) => {
    // 🔹 If a single teacher is passed, use it; otherwise use draggedTeacher; 
    // (Note: This function still works for ClassTeacher assignment which is usually 1:1)
    const t = teacher || draggedTeacher || (selectedTeachers.length > 0 ? selectedTeachers[0] : null);
    
    if (!t) {
      setActiveClassDetail(className);
      return;
    }
    setLoading(true);

    try {
      const classRef = doc(db, "classes", classDocId(className));
      const classSnap = await getDoc(classRef);

      if (!classSnap.exists()) {
        await setDoc(classRef, {
          schoolId,
          academicYear: normalizedAcademicYear,
          className,
          grade: parseInt(className.match(/^\d+/)?.[0] || "0", 10),
          division: className.replace(/^\d+/, ""),
          sectionId: activeSectionId,
          createdAt: new Date(),
        });
      }

      const classData = classSnap.data();
      const oldTeacherId = classData?.classTeacherId;

      if (oldTeacherId === t.id) {
        setLoading(false);
        return;
      }

      if (oldTeacherId) {
        const oldTeacherRef = doc(db, "users", oldTeacherId);
        const oldSnap = await getDoc(oldTeacherRef);
        if (oldSnap.exists() && oldSnap.data().assignedClass === className) {
          await updateDoc(oldTeacherRef, {
            role: "teacher",
            assignedClass: null,
            updatedAt: new Date(),
          });
        }
      }

      await updateDoc(classRef, {
        classTeacherId: t.id,
        classTeacherName: t.name,
        classTeacherEmail: t.email,
        updatedAt: new Date(),
      });

      await updateDoc(doc(db, "users", t.id), {
        role: "class_teacher",
        assignedClass: className,
        assignedClasses: [...new Set([...(t.assignedClasses || []), className])],
        updatedAt: new Date(),
      });

      await createDefaultRollSetup(schoolId, normalizedAcademicYear, className);
    } catch (err) {
      console.error("Assignment failed:", err);
    } finally {
      setDraggedTeacher(null);
      setSelectedTeachers([]); // 🔹 Reset selection
      setLoading(false);
    }
  };

  // ❌ Remove teacher
  const doRemoveTeacher = async (className) => {
    setLoading(true);
    try {
      const classRef = doc(db, "classes", classDocId(className));
      const snap = await getDoc(classRef);
      if (!snap.exists()) return;

      const data = snap.data();
      const teacherId = data.classTeacherId;

      await updateDoc(classRef, {
        classTeacherId: null,
        classTeacherName: null,
        classTeacherEmail: null,
        updatedAt: new Date(),
      });

      if (teacherId) {
        const teacherRef = doc(db, "users", teacherId);
        const tSnap = await getDoc(teacherRef);
        if (tSnap.exists() && tSnap.data().assignedClass === className) {
          await updateDoc(teacherRef, {
            role: "teacher",
            assignedClass: null,
            updatedAt: new Date(),
          });
        }
      }
    } catch (err) {
      console.error("Failed to remove teacher", err);
    } finally {
      setConfirmModal(null);
      setLoading(false);
    }
  };

  // 🗑️ Delete class
  const doDeleteClass = async (className) => {
    setLoading(true);
    try {
      const ref = doc(db, "classes", classDocId(className));
      const snap = await getDoc(ref);
      if (!snap.exists()) return;

      const data = snap.data();
      const teacherId = data.classTeacherId;

      if (teacherId) {
        const teacherRef = doc(db, "users", teacherId);
        const tSnap = await getDoc(teacherRef);
        if (tSnap.exists() && tSnap.data().assignedClass === className) {
          await updateDoc(teacherRef, {
            role: "teacher",
            assignedClass: null,
            updatedAt: new Date(),
          });
        }
      }

      await deleteDoc(ref);
    } catch (err) {
      console.error("Class deletion failed", err);
    } finally {
      setConfirmModal(null);
      setLoading(false);
    }
  };

  const renderGradeRow = (grade) => {
    const divisions = getDivisionsForGrade(grade);
    const hasClasses = divisions.length > 0;
    const isCreatorOpen = openCreatorGrade === grade;
    return (
      <div className="grade-row" key={grade}>
        <div className="grade-label">Grade {grade}</div>
        <div className="grade-boxes">
          {divisions.map((div) => {
            const className = `${grade}${div}`;
            const cls = classesMap[className];
            const hasTeacher = Boolean(cls?.classTeacherName);

            return (
              <div
                key={className}
                className="class-box"
                onClick={() => setActiveClassDetail(className)}
                onDragOver={(e) => e.preventDefault()}
                onDrop={() => assignTeacher(className, null)}
              >
                {hasTeacher ? (
                  <div className="assigned">
                    <div className="assigned-info">
                      <div className="class-name">{className}</div>
                      <div className="teacher-name">{cls.classTeacherName}</div>
                    </div>
                    <div className="assigned-actions">
                      <button
                        className="remove-btn"
                        title="Remove Teacher"
                        onClick={(e) => {
                          e.stopPropagation();
                          setConfirmModal({ type: "removeTeacher", className });
                        }}
                      >
                        -
                      </button>
                      <button
                        className="delete-btn"
                        title="Delete Class"
                        onClick={(e) => {
                          e.stopPropagation();
                          setConfirmModal({ type: "deleteClass", className });
                        }}
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="empty-slot">
                    <button
                      className="add-slot"
                      onClick={(e) => {
                        e.stopPropagation();
                        assignTeacher(className, null);
                      }}
                    >
                      Open ({className})
                    </button>
                    <div className="assigned-actions" style={{ position: 'absolute', right: '5px', top: '5px' }}>
                       <button
                        className="delete-btn"
                        onClick={(e) => {
                          e.stopPropagation();
                          setConfirmModal({ type: "deleteClass", className });
                        }}
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}

          {!hasClasses && !isCreatorOpen ? (
            <button
              type="button"
              className="grade-add-trigger"
              onClick={() => openGradeCreator(grade)}
            >
              <span>+</span>
              Add class
            </button>
          ) : null}

          {isCreatorOpen ? (
            <div className="grade-creator-card">
              <div className="grade-creator-head">
                <strong>Create Grade {grade}</strong>
                <button type="button" className="grade-creator-close" onClick={closeGradeCreator}>
                  ×
                </button>
              </div>
              <div className="grade-creator-grid">
                <label>
                  <span>Division format</span>
                  <select
                    value={getDivisionFormatForGrade(grade)}
                    onChange={(e) =>
                      setDivisionFormatByGrade((prev) => ({ ...prev, [grade]: e.target.value }))
                    }
                  >
                    {DIVISION_FORMATS.map((format) => (
                      <option key={format.id} value={format.id}>
                        {format.label}
                      </option>
                    ))}
                  </select>
                </label>
                <label>
                  <span>How many divisions</span>
                  <input
                    type="number"
                    min="1"
                    max="12"
                    value={getDivisionCountForGrade(grade)}
                    onChange={(e) =>
                      setDivisionCountByGrade((prev) => ({
                        ...prev,
                        [grade]: Math.max(1, Number(e.target.value || 1)),
                      }))
                    }
                  />
                </label>
                {getDivisionFormatForGrade(grade) === "custom" ? (
                  <label>
                    <span>Custom prefix</span>
                    <input
                      type="text"
                      value={getCustomPrefixForGrade(grade)}
                      onChange={(e) =>
                        setCustomPrefixByGrade((prev) => ({
                          ...prev,
                          [grade]: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""),
                        }))
                      }
                      placeholder="Ex: X"
                    />
                  </label>
                ) : null}
              </div>
              <div className="grade-creator-actions">
                <button
                  type="button"
                  className="grade-creator-primary"
                  onClick={() => handleCreateGradeClasses(grade)}
                >
                  Create classes
                </button>
              </div>
            </div>
          ) : null}

          {hasClasses ? (
            <div className="grade-inline-actions">
              <div className="add-division">
                <input
                  type="text"
                  placeholder="New Div"
                  value={newDivisionInput[grade] || ""}
                  onChange={(e) =>
                    setNewDivisionInput((p) => ({
                      ...p,
                      [grade]: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""),
                    }))
                  }
                  onKeyDown={(e) =>
                    e.key === "Enter" && handleAddDivision(grade, newDivisionInput[grade])
                  }
                />
                <button
                  className="add-division-btn"
                  onClick={() => handleAddDivision(grade, newDivisionInput[grade])}
                >
                  Add division
                </button>
              </div>
              <button
                type="button"
                className="grade-add-trigger compact"
                onClick={() => openGradeCreator(grade)}
              >
                + Batch create
              </button>
            </div>
          ) : null}
        </div>
      </div>
    );
  };

  return (
    <div className="ctm-container">
      <div className="ctm-header">
        <h2 className="gradient-text">
          {activeClassDetail ? `Class Details` : "Class Teacher Management"}
        </h2>
        {loading && <div className="saving">Saving...</div>}
      </div>

      <div className="ctm-main">
        <div className="left-panel">
          {activeClassDetail ? (
            <ClassDetailView
              className={activeClassDetail}
              schoolId={schoolId}
              school={school}
              academicYear={normalizedAcademicYear}
              teachers={teachers}
              draggedTeacher={draggedTeacher}
              setDraggedTeacher={setDraggedTeacher}
              selectedTeachers={selectedTeachers}
              setSelectedTeachers={setSelectedTeachers}
              onBack={() => setActiveClassDetail(null)}
              mode="admin"
            />
          ) : (
            <>
              <div className="tabs1">
                {sections.map((s) => (
                  <button
                    key={s.id}
                    className={`tab ${s.id === activeSectionId ? "active" : ""}`}
                    onClick={() => setActiveSectionId(s.id)}
                  >
                    {s.label}
                  </button>
                ))}
              </div>
              <div className="class-flow-note">
                Start with no prebuilt class boxes. Use the <strong>+</strong> button inside each grade row to create classes and choose the division format directly in this section.
              </div>
              <div className="grades-area">
                {activeSection.grades.map((g) => renderGradeRow(g))}
              </div>
            </>
          )}
        </div>

        <div className="right-panel">
          <TeacherList
            teachers={filteredTeachers}
            
            /* 🔹 PASSING PLURAL PROPS TO TeacherList */
            selectedTeachers={selectedTeachers}
            setSelectedTeachers={setSelectedTeachers}
            
            draggedTeacher={draggedTeacher}
            setDraggedTeacher={setDraggedTeacher}
            searchTerm={searchTerm}
            setSearchTerm={setSearchTerm}
          />
        </div>
      </div>

      {confirmModal && (
        <div className="ctm-modal-overlay" onClick={() => setConfirmModal(null)}>
          <div className="ctm-modal" onClick={(e) => e.stopPropagation()}>
            <h4>Confirm</h4>
            <p>
              {confirmModal.type === "removeTeacher"
                ? `Remove teacher from ${confirmModal.className}?`
                : `Delete class ${confirmModal.className} entirely?`}
            </p>
            <div className="modal-actions">
              <button className="modal-cancel" onClick={() => setConfirmModal(null)}>Cancel</button>
              <button
                className="modal-confirm"
                onClick={() =>
                  confirmModal.type === "removeTeacher"
                    ? doRemoveTeacher(confirmModal.className)
                    : doDeleteClass(confirmModal.className)
                }
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ClassTeacherManager;
