import React, { useEffect, useState, useMemo } from "react";
import {
  collection,
  query,
  where,
  onSnapshot,
  doc,
  setDoc,
  deleteDoc,
  getDoc,
  getDocs,
  updateDoc,
  writeBatch,
} from "firebase/firestore";
import { db } from "../../../../firebase/firebaseConfig";
import "./ClassTeacherManager.css";
import ClassDetailView from "./ClassTeacherManager/ClassDetailView";
import TeacherList from "./ClassTeacherManager/TeacherList";

// =========================================
// CONFIG
// =========================================
const DEFAULT_SECTIONS = [
  { id: "1-5", label: "1 - 5", grades: [1, 2, 3, 4, 5] },
  { id: "6-9", label: "6 - 9", grades: [6, 7, 8, 9] },
  { id: "10-12", label: "10 - 12", grades: [10, 11, 12] },
];

// =========================================
// HELPER: Auto-create Roll Setup
// =========================================
const createDefaultRollSetup = async (schoolId, className) => {
  try {
    const classId = `${schoolId}_${className}`;
    const rollSetupRef = doc(db, "classes", classId, "meta", "rollSetup");
    const studentsRef = collection(db, "classes", classId, "students");

    const grade = parseInt(className.match(/^\d+/)?.[0] || "0", 10);
    const total = grade <= 5 ? 25 : grade <= 9 ? 35 : 40;
    const rolls = Array.from({ length: total }, (_, i) => (i + 1).toString());

    const rollSnap = await getDoc(rollSetupRef);
    if (rollSnap.exists()) return;

    const batch = writeBatch(db);
    batch.set(rollSetupRef, {
      studentCount: total,
      format: "numeric",
      prefix: "",
      range: { start: 1, end: total },
      createdAt: new Date(),
      autoGenerated: true,
    });

    rolls.forEach((roll) => {
      const studentRef = doc(studentsRef, roll);
      batch.set(studentRef, {
        rollNumber: roll,
        name: `Student ${roll}`,
        attendance: {},
        performance: {},
        createdAt: new Date(),
      });
    });

    await batch.commit();
    console.log(`✅ Default roll setup created for ${className}`);
  } catch (err) {
    console.error("❌ Roll setup creation failed:", err);
  }
};

// =========================================
// MAIN COMPONENT
// =========================================
const ClassTeacherManager = ({ schoolId }) => {
  const [sections] = useState(DEFAULT_SECTIONS);
  const [activeSectionId, setActiveSectionId] = useState(DEFAULT_SECTIONS[0].id);
  const [classesMap, setClassesMap] = useState({});
  const [teachers, setTeachers] = useState([]);
  const [filteredTeachers, setFilteredTeachers] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [draggedTeacher, setDraggedTeacher] = useState(null);
  const [selectedTeacher, setSelectedTeacher] = useState(null);
  const [loading, setLoading] = useState(false);
  const [newDivisionInput, setNewDivisionInput] = useState({});
  const [confirmModal, setConfirmModal] = useState(null);
  const [activeClassDetail, setActiveClassDetail] = useState(null);

  // =========================================
  // Realtime Teachers
  // =========================================
  useEffect(() => {
    if (!schoolId) return;
    const q = query(collection(db, "users"), where("schoolId", "==", schoolId));
    const unsub = onSnapshot(q, (snap) => {
      const list = snap.docs
        .map((d) => ({ id: d.id, ...d.data() }))
        .filter((t) => ["teacher", "class_teacher"].includes(t.role)); // ✅ Only teachers

      setTeachers(list);
      setFilteredTeachers(list);
    });

    return () => unsub();
  }, [schoolId]);

  // =========================================
  // Realtime Classes
  // =========================================
  useEffect(() => {
    if (!schoolId) return;
    const q = query(collection(db, "classes"), where("schoolId", "==", schoolId));
    const unsub = onSnapshot(q, (snap) => {
      const map = {};
      snap.docs.forEach((d) => (map[d.data().className] = { id: d.id, ...d.data() }));
      setClassesMap(map);
    });
    return () => unsub();
  }, [schoolId]);

  // =========================================
  // Search Filter
  // =========================================
  useEffect(() => {
    const lower = searchTerm.trim().toLowerCase();
    setFilteredTeachers(
      !lower
        ? teachers
        : teachers.filter(
          (t) =>
            (t.name || "").toLowerCase().includes(lower) ||
            (t.email || "").toLowerCase().includes(lower)
        )
    );
  }, [searchTerm, teachers]);

  // =========================================
  // HELPERS
  // =========================================
  const classDocId = (className) => `${schoolId}_${className}`;
  const activeSection = useMemo(
    () => sections.find((s) => s.id === activeSectionId),
    [sections, activeSectionId]
  );

  const getDivisionsForGrade = (grade) => {
    const gradeClasses = Object.values(classesMap).filter((c) => c.grade === grade);
    const divs = Array.from(
      new Set(gradeClasses.map((c) => c.division || c.className.replace(/^\d+/, "")))
    );
    return divs.length ? divs : ["A"];
  };

  // =========================================
  // CLASS OPERATIONS
  // =========================================

  // ➕ Add new division
  const handleAddDivision = async (grade, divRaw) => {
    const division = (divRaw || "").trim().toUpperCase();
    if (!division) return alert("Enter valid division");
    const className = `${grade}${division}`;
    setLoading(true);
    try {
      const ref = doc(db, "classes", classDocId(className));
      const snap = await getDoc(ref);
      if (snap.exists()) {
        alert(`${className} already exists`);
      } else {
        await setDoc(ref, {
          schoolId,
          className,
          grade,
          division,
          sectionId: activeSectionId,
          createdAt: new Date(),
        });
      }
      setNewDivisionInput((p) => ({ ...p, [grade]: "" }));
    } catch (err) {
      console.error("Error adding division", err);
    } finally {
      setLoading(false);
    }
  };

  // 👩‍🏫 Assign teacher to class (handles replacement)
  const assignTeacher = async (className, teacher) => {
    const t = teacher || draggedTeacher || selectedTeacher;
    if (!t) return alert("Select or drag a teacher first");
    setLoading(true);

    try {
      const classRef = doc(db, "classes", classDocId(className));
      const classSnap = await getDoc(classRef);

      // Ensure class exists
      if (!classSnap.exists()) {
        await setDoc(classRef, {
          schoolId,
          className,
          grade: parseInt(className.match(/^\d+/)?.[0] || "0", 10),
          division: className.replace(/^\d+/, ""),
          sectionId: activeSectionId,
          createdAt: new Date(),
        });
      }

      const classData = classSnap.data();
      const oldTeacherId = classData?.classTeacherId;

      // If same teacher already assigned
      if (oldTeacherId === t.id) {
        setLoading(false);
        return;
      }

      // 1️⃣ Unassign old teacher (if exists)
      if (oldTeacherId) {
        const oldTeacherRef = doc(db, "users", oldTeacherId);
        const oldSnap = await getDoc(oldTeacherRef);
        if (oldSnap.exists()) {
          const oldData = oldSnap.data();
          if (oldData.assignedClass === className) {
            await updateDoc(oldTeacherRef, {
              role: "teacher",
              assignedClass: null,
              updatedAt: new Date(),
            });
          }
        }
      }

      // 2️⃣ Assign new teacher
      await updateDoc(classRef, {
        classTeacherId: t.id,
        classTeacherName: t.name,
        classTeacherEmail: t.email,
        updatedAt: new Date(),
      });

      await updateDoc(doc(db, "users", t.id), {
        role: "class_teacher",
        assignedClass: className,
        assignedClasses: [...new Set([...(t.assignedClasses || []), className])],
        updatedAt: new Date(),
      });

      // 3️⃣ Create roll setup only if missing
      await createDefaultRollSetup(schoolId, className);

      console.log(`✅ ${t.name} assigned to ${className}`);
    } catch (err) {
      console.error("Assignment failed:", err);
    } finally {
      setDraggedTeacher(null);
      setSelectedTeacher(null);
      setLoading(false);
    }
  };

  // ❌ Remove teacher from class
  const doRemoveTeacher = async (className) => {
    setLoading(true);
    try {
      const classRef = doc(db, "classes", classDocId(className));
      const snap = await getDoc(classRef);
      if (!snap.exists()) return;

      const data = snap.data();
      const teacherId = data.classTeacherId;

      await updateDoc(classRef, {
        classTeacherId: null,
        classTeacherName: null,
        classTeacherEmail: null,
        updatedAt: new Date(),
      });

      if (teacherId) {
        const teacherRef = doc(db, "users", teacherId);
        const tSnap = await getDoc(teacherRef);
        if (tSnap.exists() && tSnap.data().assignedClass === className) {
          await updateDoc(teacherRef, {
            role: "teacher",
            assignedClass: null,
            updatedAt: new Date(),
          });
        }
      }

      console.log(`🔸 Teacher removed from ${className}`);
    } catch (err) {
      console.error("Failed to remove teacher", err);
    } finally {
      setConfirmModal(null);
      setLoading(false);
    }
  };

  // 🗑️ Delete class (safe cleanup)
  const doDeleteClass = async (className) => {
    setLoading(true);
    try {
      const ref = doc(db, "classes", classDocId(className));
      const snap = await getDoc(ref);
      if (!snap.exists()) return;

      const data = snap.data();
      const teacherId = data.classTeacherId;

      if (teacherId) {
        const teacherRef = doc(db, "users", teacherId);
        const tSnap = await getDoc(teacherRef);
        if (tSnap.exists() && tSnap.data().assignedClass === className) {
          await updateDoc(teacherRef, {
            role: "teacher",
            assignedClass: null,
            updatedAt: new Date(),
          });
        }
      }

      await deleteDoc(ref);
      console.log(`🗑️ Class ${className} deleted`);
    } catch (err) {
      console.error("Class deletion failed", err);
    } finally {
      setConfirmModal(null);
      setLoading(false);
    }
  };

  // =========================================
  // UI: Render Grade Row
  // =========================================
  const renderGradeRow = (grade) => {
    const divisions = getDivisionsForGrade(grade);
    return (
      <div className="grade-row" key={grade}>
        <div className="grade-label">Grade {grade}</div>
        <div className="grade-boxes">
          {divisions.map((div) => {
            const className = `${grade}${div}`;
            const cls = classesMap[className];
            const hasTeacher = Boolean(cls?.classTeacherName);

            return (
              <div
                key={className}
                className="class-box"
                onClick={() => setActiveClassDetail(className)}
                onDragOver={(e) => e.preventDefault()}
                onDrop={() => assignTeacher(className, null)}
              >
                {hasTeacher ? (
                  <div className="assigned">
                    <div className="assigned-info">
                      <div className="class-name">{className}</div>
                      <div className="teacher-name">{cls.classTeacherName}</div>
                    </div>
                    <div className="assigned-actions">
                      <button
                        className="remove-btn"
                        onClick={(e) => {
                          e.stopPropagation();
                          setConfirmModal({ type: "removeTeacher", className });
                        }}
                      >
                        -
                      </button>
                      <button
                        className="delete-btn"
                        onClick={(e) => {
                          e.stopPropagation();
                          setConfirmModal({ type: "deleteClass", className });
                        }}
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="empty-slot">
                    <button
                      className="add-slot"
                      onClick={(e) => {
                        e.stopPropagation();
                        assignTeacher(className, null);
                      }}
                    >
                      ＋ Assign Teacher ({className})
                    </button>
                  </div>
                )}
              </div>
            );
          })}

          <div className="add-division">
            <input
              type="text"
              placeholder="New Div (e.g. B)"
              value={newDivisionInput[grade] || ""}
              onChange={(e) =>
                setNewDivisionInput((p) => ({
                  ...p,
                  [grade]: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""),
                }))
              }
              onKeyDown={(e) =>
                e.key === "Enter" && handleAddDivision(grade, newDivisionInput[grade])
              }
            />
            <button
              className="add-division-btn"
              onClick={() => handleAddDivision(grade, newDivisionInput[grade])}
            >
              Add
            </button>
          </div>
        </div>
      </div>
    );
  };

  // =========================================
  // MAIN RENDER
  // =========================================
  return (
    <div className="ctm-container">
      <div className="ctm-header">
        <h2 className="gradient-text">
          {activeClassDetail ? `Class Details` : "Class Teacher Management"}
        </h2>
        {loading && <div className="saving">Saving...</div>}
      </div>

      <div className="ctm-main">
        <div className="left-panel">
          {activeClassDetail ? (
            <ClassDetailView
              className={activeClassDetail}
              schoolId={schoolId}
              teachers={teachers}
              draggedTeacher={draggedTeacher}
              setDraggedTeacher={setDraggedTeacher}
              onBack={() => setActiveClassDetail(null)}
              mode="admin"
            />
          ) : (
            <>
              <div className="tabs1">
                {sections.map((s) => (
                  <button
                    key={s.id}
                    className={`tab ${s.id === activeSectionId ? "active" : ""}`}
                    onClick={() => setActiveSectionId(s.id)}
                  >
                    {s.label}
                  </button>
                ))}
              </div>
              <div className="grades-area">
                {activeSection.grades.map((g) => renderGradeRow(g))}
              </div>
            </>
          )}
        </div>

        <div className="right-panel">
          <TeacherList
            teachers={filteredTeachers}
            selectedTeacher={selectedTeacher}
            setSelectedTeacher={setSelectedTeacher}
            draggedTeacher={draggedTeacher}
            setDraggedTeacher={setDraggedTeacher}
            searchTerm={searchTerm}
            setSearchTerm={setSearchTerm}
          />
        </div>
      </div>

      {confirmModal && (
        <div className="ctm-modal-overlay" onClick={() => setConfirmModal(null)}>
          <div className="ctm-modal" onClick={(e) => e.stopPropagation()}>
            <h4>Confirm</h4>
            <p>
              {confirmModal.type === "removeTeacher"
                ? `Remove teacher from ${confirmModal.className}?`
                : `Delete ${confirmModal.className}?`}
            </p>
            <div className="modal-actions">
              <button onClick={() => setConfirmModal(null)}>Cancel</button>
              <button
                className="modal-confirm"
                onClick={() =>
                  confirmModal.type === "removeTeacher"
                    ? doRemoveTeacher(confirmModal.className)
                    : doDeleteClass(confirmModal.className)
                }
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ClassTeacherManager;
